name: ctse_lecture2
description: Flutter project for CTSE Lecture 2.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/dart_logo.png

  fonts:
    - family: KungfuMaster
      fonts:
        - asset: lib/assets/fonts/kungfumaster.ttf
